// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_1YXjFGv7kdIxvPioZeAyPIVUAcNxCAE',
    appId: '1:740476099811:android:34064886c23070ca0ff9d6',
    messagingSenderId: '740476099811',
    projectId: 'gchat-a63d1',
    storageBucket: 'gchat-a63d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj12iBXcm0djD0kKyCEmSu05YbclYIFRs',
    appId: '1:740476099811:ios:c33588eb3ec577330ff9d6',
    messagingSenderId: '740476099811',
    projectId: 'gchat-a63d1',
    storageBucket: 'gchat-a63d1.firebasestorage.app',
    iosBundleId: 'com.app.gchat',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHkqwn3qXuy_NbLz1m3vnww3X_halIxrk',
    appId: '1:740476099811:web:b159bf4d446e6a480ff9d6',
    messagingSenderId: '740476099811',
    projectId: 'gchat-a63d1',
    authDomain: 'gchat-a63d1.firebaseapp.com',
    storageBucket: 'gchat-a63d1.firebasestorage.app',
  );

}